title: Life
description: Life
theme: just-the-docs

url: https://github.com/haydnjonesdesign/life

aux_links:
  Repository: https://github.com/haydnjonesdesign/life

plugins:
  - jekyll-default-layout
